use_frameworks!

target 'iAirportsDB_Example' do
  pod 'iAirportsDB', :path => '../'

  target 'iAirportsDB_Tests' do
    inherit! :search_paths

#pod 'Quick', :git => "https://github.com/Quick/Quick", :branch => "swift-3.0"
pod 'Quick'
#pod 'Nimble', :git => "https://github.com/martnst/Nimble", :branch => "swift3"
pod 'Nimble' #, '~> 3.0'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
