use_frameworks!

target 'iAirportsDB_Example' do
  pod 'iAirportsDB', :path => '../'

  target 'iAirportsDB_Tests' do
    inherit! :search_paths

    #pod 'Quick', :git => "https://github.com/Quick/Quick", :branch => "swift-3.0"
    pod 'Quick'
    #pod 'Nimble', :git => "https://github.com/martnst/Nimble", :branch => "swift3"
    pod 'Nimble' , '~> 7.0'
  end
end

